profile=high-quality
vo=gpu-next
scale-antiring=0.6
gpu-api=vulkan
hwdec=auto-copy
# dither-depth = 10 # change accordingly
# target-colorspace-hint=yes

deband=no
deband-iterations=2
deband-threshold=64
deband-range=20
deband-grain=64

osc = no
osd-bar=no
border = no
keep-open = yes
sub-codepage = utf-8
osd-status-msg=${playback-time/full} / ${duration} (${percent-pos}%)\nframe: ${estimated-frame-number} / ${estimated-frame-count}

screenshot-format = png
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

sub-ass-override=no # toggled w/ k
sub-font = "Gandhi Sans"
sub-font-size = 50
sub-color="#FFFFFF"
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-border-size = 2.4
sub-shadow-offset = 0.75
sub-bold = yes
sub-margin-x = 40
sub-margin-y = 40

alang=ja,jp,jpn,en,eng
slang=eng,en,enm
volume-max=300

[simulcast]
profile-cond=(function(a)for b,c in ipairs(a)do if filename:match(c)then return true end end end)({"SubsPlease","Erai%-raws","Tsundere%-Raws","%-VARYG","HorribleSubs","SubsPlus%+", "Yameii", "ToonsHub"})
profile-restore=copy
deband=yes